### ISSUE TITLE
Smiling face with tear "Color" version has a purple mouth

### ISSUE THREAD

**Issue by LouanBen** [microsoft/fluentui-emoji#54]
Everything is in the title. I don't get why this one has a purple mouth (#533468) instead of the regual brown-ish color.

I think it's due to the fact that the gradient used on the other mouths didn't apply to this one.

**Comment by jasoncuster** [comment]
Hey @LouanBen, can you share what you're seeing? We re-exported it, and don't see the issue you're seeing.

**Comment by ThioJoe** [comment]
I think I see what he's saying. The mouth looks more purple than the others. Could be intentional though.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/12518330/189492072-e3b72fe4-11ec-4c3b-8c0e-c013a7b905e5.png">

<img width="500" alt="image" src="https://user-images.githubusercontent.com/12518330/189492084-1cc248bb-caba-4fff-9b09-35e5b00d2573.png">

<img width="500" alt="image" src="https://user-images.githubusercontent.com/12518330/189492098-a6e65542-8fc7-4c61-8566-09c2dfa3d7cb.png">

**Comment by jasoncuster** [comment]
We've added an update to the newest bug fix branch. Unsure on timing but will note it here when done.

**Comment by jasoncuster** [comment]
This fix has been implemented. Thank you!
