### ISSUE TITLE
A copyright related question

### ISSUE THREAD

**Issue by eve33333** [microsoft/fluentui-emoji#81]
Hi,
If I want to use emojis to make a promo banner, which is not commercial, where do I need to put a copyright?

**Comment by spencer-nelson** [comment]
Apologies for the licensing confusion. These are released public/open and there isn't currently a requirement for copyright publishing for usage like that, of which I am aware. If you ever run into Mr. Custer IRL feel welcome to tell him how awesome he is for his work with all this, but otherwise you should be good to go. ;)
